#!/usr/bin/env bash
date=$(date +%F);
record=$(date +%H:%M:%S);
if [ ! -d "$HOME/usage" ]; then
    mkdir "$HOME/usage";
fi
if [ ! -d "$HOME/usage/$date" ]; then
    mkdir "$HOME/usage/$date";
fi
if [ -f "$HOME/usage/$date/$record.txt" ]; then
    rm "$HOME/usage/$date/$record.txt";
fi
echo $(date) >> $HOME/usage/$date/$record.txt
echo "
\
memory info:_________________________________________________________
\
" >> $HOME/usage/$date/$record.txt
sed -n '1,7p' /proc/meminfo >> "$HOME/usage/$date/$record.txt"
echo "
\
storage space:_______________________________________________________
\
" >> $HOME/usage/$date/$record.txt
df -h | sed -n 1,2p | cut -c 1-10,50-100 >> "$HOME/usage/$date/$record.txt"
echo " 
top procceses:_______________________________________________________
" >> "$HOME/usage/$date/$record.txt"
ps -eo pcpu,pmem,pid,user,args | sort -r -k1 | less | sed -n '1,11p' >> "$HOME/usage/$date/$record.txt"
echo "
\
Network:_____________________________________________________________
\
" >> "$HOME/usage/$date/$record.txt"
/sbin/ifconfig |grep -B1 "inet addr" >> "$HOME/usage/$date/$record.txt"
echo "Your usage has been recorded in ~/usage/$date/$record.txt";
