#!/usr/bin/env bash
date=$(date +%F);
record=$(date +%H:%M:%S);

if [ ! -d "$HOME/usage" ]; then
    mkdir "$HOME/usage";
fi

if [ ! -d "$HOME/usage/$date" ]; then
    mkdir "$HOME/usage/$date";
fi

if [ -f "$HOME/usage/$date/$record.txt" ]; then
    rm "$HOME/usage/$date/$record.txt";
fi

echo $(date) >> $HOME/usage/$date/$record.txt
echo "memory info:
\
" >> $HOME/usage/$date/$record.txt
sed -n '1,7p' /proc/meminfo >> "$HOME/usage/$date/$record.txt"
echo "\
"
echo "
storage space:
\
" >> $HOME/usage/$date/$record.txt
df -h | sed -n 1p >> "$HOME/usage/$date/$record.txt"
df -h | sed -n 2p >> "$HOME/usage/$date/$record.txt"

echo "\
Your usage has been recorded in ~/usage/$date/$record.txt";
