#!/usr/bin/env bash
date=$(date +%F);

if [ ! -d "$HOME/usage" ]; then
    mkdir "$HOME/usage";
fi

if [ -f "$HOME/usage/$date.txt" ]; then
    rm "$HOME/usage/$date.txt";
fi

echo $(date) >> $HOME/usage/$date.txt
echo "memory info:
\
" >> $HOME/usage/$date.txt
sed -n '1,7p' /proc/meminfo >> "$HOME/usage/$date.txt"
